### ISSUE TITLE
A hard-to-follow documentation

### ISSUE THREAD

**Issue by smnbbrv** [troyanskiy/ngx-resource#101]
maybe it's my feeling only, but the documentation becomes so long that it is really hard to understand what and when was changed; it consists of different mixed things such as examples, explanations, API etc.

Would it be useful to make some sort of well structured [github pages](https://pages.github.com/) documentation? Ideally the examples and typical setups should go to a separate folder, maybe with a demo.

**Comment by troyanskiy** [comment]
Hello.
Yes, I agree with you. I will do it when I will have time.
If you wish, you can help with that with PR.
Just create all the pages in docs folder.

Thank you!

**Comment by beradrian** [comment]
I would just move the documentation for each class in a separate file/folder. And for keeping track of the changes I would use the GitHub releases to have it in a structured way.
And the examples would be good to be on something like plunkr (the server side part can be some static file maybe using github pages)

Otherwise the documentation looks ok and I had no problem using this library.

**Comment by troyanskiy** [comment]
Hello all.

I've released some kind of beta of new library which is called `rest-core` + `rest-ngx`.
Please check them [`rest-core`](https://www.npmjs.com/package/rest-core) and [`rest-ngx`](https://www.npmjs.com/package/rest-ngx).

It works the way like `ngx-resource` but has a lot of breaking changes.
Something was removed or simplified.

I've migrated all my projects to the new library.
If you wish to switch to HttpClient or use some other http handlers like `fetch` try to migrate your projects to the lib.

Bugs and help requests are welcome in corresponding repos.

Thanks!

PS: Since `ngx-resource` is no longer supported by me, closing the issue.
