### ISSUE TITLE
[Question] Is a way to send FormData object in the request.

### ISSUE THREAD

**Issue by JulioWar** [troyanskiy/ngx-resource#115]
Hello @troyanskiy
I was wondering if is possible to send `FormData` object using `ResourceModel`. 
The reason to do that is because I want to send a file in the request.
Thanks

**Comment by troyanskiy** [comment]
Hello.
I don't think it's possible to do that with the library and with angular http nether.
To upload file I was creating XHR request.
Please check here https://stackoverflow.com/questions/32423348/angular2-post-uploaded-file

**Comment by JulioWar** [comment]
Actually, I was look in this [gist](https://gist.github.com/arciisine/ee57727e56cbc5e83739b2c24fd69658). I tried it and it worked. 
But how can achieve that with this library?

**Comment by troyanskiy** [comment]
It look's interesting.
I will do something for that.

**Comment by maxkorz** [comment]
@JulioWar @troyanskiy 
Actually it's pretty easy. Working example here: https://stackblitz.com/edit/angular-g5oxpu

all the magic is below:
```ts
export class FileUploadRes extends Resource {
  @ResourceAction({
    method: RequestMethod.Post,
    headers: {
      'Content-Type': undefined, // let browser handle it
    },
    bodySerializer(data) {
      const formData = new FormData();
      formData.append('file', data.file);

      return formData as any;
    },
    requestInterceptor(req: Request): Request {
      req.headers.delete('Content-Type'); // let browser handle it
      return req;
    },
  })
  public upload: ResourceMethod<{ file: any }, any>;
}
```

**Comment by troyanskiy** [comment]
Hello all.

I've released some kind of beta of new library which is called `rest-core` + `rest-ngx`.
Please check them [`rest-core`](https://www.npmjs.com/package/rest-core) and [`rest-ngx`](https://www.npmjs.com/package/rest-ngx).

It works the way like `ngx-resource` but has a lot of breaking changes.
Something was removed or simplified.

I've migrated all my projects to the new library.
If you wish to switch to HttpClient or use some other http handlers like `fetch` try to migrate your projects to the lib.

Bugs and help requests are welcome in corresponding repos.

Thanks!

PS: Since `ngx-resource` is no longer supported by me, closing the issue.
