### ISSUE TITLE
Support for HttpClient

### ISSUE THREAD

**Issue by Crysalist** [troyanskiy/ngx-resource#130]
Any change of getting a version / branch that supports the new HttpClient that was added in 4.3 of angular? 

https://angular.io/guide/http

**Comment by troyanskiy** [comment]
Hello.
I did not check that new HttpClient from new Angular 4.3 yet.
Is there any reason or advantage to use HttpClient instead of Http?

**Comment by Crysalist** [comment]
You can intercept the requests. So if you use it, it can integrate with your loaders/jwt token handlers etc.

**Comment by kptLucek** [comment]
:+1: For `HttpClient` instead of `Http`

**Comment by troyanskiy** [comment]
Hello.
For now, I don't see any urgency to move from Http to HttpClient.
1. It will not be compatible with angular versions lower than 4.3; (this is main reason)
1. Http is not deprecated by Angular;
1. @Crysalist you can intercept the requests also with Http

I will keep the issue open for future.

Thank you.

**Comment by Crysalist** [comment]
👌  I wrote my own thank-you for getting back to me.

**Comment by kuhnroyal** [comment]
It would be nice to have 2 modules, one for `Http` and one for `HttpClient`. Maybe keep this issue open?

**Comment by troyanskiy** [comment]
I will try to find a time to make a separate version with `HttpClient`.
Let's keep the issue open.

**Comment by troyanskiy** [comment]
Hello all.

I've released some kind of beta of new library which is called `rest-core` + `rest-ngx`.
Please check them [`rest-core`](https://www.npmjs.com/package/rest-core) and [`rest-ngx`](https://www.npmjs.com/package/rest-ngx).

It works the way like `ngx-resource` but has a lot of breaking changes.
Something was removed or simplified.

I've migrated all my projects to the new library.
If you wish to switch to HttpClient or use some other http handlers like `fetch` try to migrate your projects to the lib.

Bugs and help requests are welcome in corresponding repos.

Thanks!

PS: Since `ngx-resource` is no longer supported by me, closing the issue.
