### ISSUE TITLE
Post string to body

### ISSUE THREAD

**Issue by JureFadiga1** [troyanskiy/ngx-resource#140]
Hello,

I am sending a post request with a data of string type in body. The string is being transformed to an object of characters.
data = "Hello"
body after prepareDataParams function = {0: "H", 1: "e", 2: "l", 3: "l", 4: "o"}
Please add prepareDataParams override method in RequestAction so we can customize the code inside it.
We tried bodySerializer method in our ResourceAction but it already gets rewritten data.

Thank you in advance

**Comment by troyanskiy** [comment]
Hello @JureFadiga1 
Thank you for the issue.
I will try to check and implement that case for you ASAP.

**Comment by troyanskiy** [comment]
Hello all.

I've released some kind of beta of new library which is called `rest-core` + `rest-ngx`.
Please check them [`rest-core`](https://www.npmjs.com/package/rest-core) and [`rest-ngx`](https://www.npmjs.com/package/rest-ngx).

It works the way like `ngx-resource` but has a lot of breaking changes.
Something was removed or simplified.

I've migrated all my projects to the new library.
If you wish to switch to HttpClient or use some other http handlers like `fetch` try to migrate your projects to the lib.

Bugs and help requests are welcome in corresponding repos.

Thanks!

PS: Since `ngx-resource` is no longer supported by me, closing the issue.
