### ISSUE TITLE
missing method $getPathPrefix

### ISSUE THREAD

**Issue by frankguns** [troyanskiy/ngx-resource#143]
Hi,

Currently we can define the properties url, pathPrefix and path on ResourceParams.
We can also call the methods $getUrl and $getPath to retrieve the values of url and path.
But there is no method $getPathPrefix to retrieve pathPrefix.

Can this be added?

Thanks!

**Comment by troyanskiy** [comment]
Hello.

I think I will no longer provide support for the library since I'm now concentrated on the new the library for rest calls.
But PR is welcome if you really need that method.

Now I'm developing/testing/debugging new library when I have time to do that. And in fact, new lib contains `$getPathPrefix`.

In case if you would like to try new lib
`$ npm i --save rest-core rest-ngx`

But for now (while I'm stabilizing the lib), I don't provide any help or any documentation for the new lib.
You can dig into the sources to check how to use it.
It works almost the same as `ngx-resource`

**Comment by troyanskiy** [comment]
Hello all.

I've released some kind of beta of new library which is called `rest-core` + `rest-ngx`.
Please check them [`rest-core`](https://www.npmjs.com/package/rest-core) and [`rest-ngx`](https://www.npmjs.com/package/rest-ngx).

It works the way like `ngx-resource` but has a lot of breaking changes.
Something was removed or simplified.

I've migrated all my projects to the new library.
If you wish to switch to HttpClient or use some other http handlers like `fetch` try to migrate your projects to the lib.

Bugs and help requests are welcome in corresponding repos.

Thanks!

PS: Since `ngx-resource` is no longer supported by me, closing the issue.
