### ISSUE TITLE
@ResourceAction decorator doesn't respect "headers" parameter

### ISSUE THREAD

**Issue by tavai89** [troyanskiy/ngx-resource#145]
Hi, I am not sure if this is not my mistake or misunderstanding, but looks like when I trying to set custom request headers the at @ResourceAction level, ngx-resource doesn't "respect" it.

 ```
@ResourceAction({
        url: AppConfig.envs[AppConfig.env].resources.base + '/Projects/{!ProjectId}/Deliverables/{!DeliverableId}/TestScenarios/{!TestScenarioId}/TestCases/{!Id}/Record',
        method: RequestMethod.Post,
        headers: {
            'Content-Type': undefined,
            'enctype': 'multipart/form-data'
        }
    })
``` 
When I sending this request and inspecting it with Chrome Dev Tools, I don't see those headers is set for this request.

Can you please help me?

Thanks in advance

**Comment by troyanskiy** [comment]
Hello.
I'm no longer providing support for the library, because I have new one.
I would offer you to try new one where it's much more easier specify request types.
Please try to switch to [`rest-core`](https://github.com/troyanskiy/rest-core) with [`rest-ngx`](https://github.com/troyanskiy/rest-ngx) module.

**Comment by tavai89** [comment]
Cool! Thank you. I will try new one 👍
